import Footer from '@/components/sharedComponents/Footer'
import Header from '@/components/sharedComponents/Header'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Task-Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
